version: "3.8"
services:
  node:
    image: "node:latest"
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
  frontend:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
